# Configuration file for TravisCI
language: python
python: "3.6"
os: linux

# Only build pushes to the master branch
branches:
  only:
    - master

# Define environment variables common to all builds
env:
  global:
    # Doctr deploy key for fatiando/fatiando.github.io
    - secure: "Qlg7kdoxrrtPpxu/kl0YoEf8PVsBmxgX+LRvsl+iSf09IO5k+d/rw7vFi/0pGBxlE1Pzd4ZzbYp186YqXNpgRMjEhGCsRkLQ0aoD9Lpx/DTaQ3yv0GseIQkPupUTQGXtuLV9tkw/GRQAeK/13DRq7RPYH32yGpIC+9MQ4CmZ/r0="

# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

# Build the documentation HTML
script:
  - make all

# Deploy the built HTML to Github pages
deploy:
  - provider: script
    script: doctr deploy . --built-docs _build/html --key-path .github_deploy_key.enc --deploy-repo fatiando/fatiando.github.io
    skip_cleanup: true
    on:
      branch: master

# Don't send out emails every time a build fails
notifications:
  email: false
